input_data:
    data_location: mock
    data_format: csv

project:
    project_name: mock_project

features:
    - 'mock-features/features.py'

feature_group:
    - MockFeatureGroup

output_data:
    output_location: mock
